falco:
  rules:
    - rule: Write below binary dir
      condition: >
        evt.dir = < and fd.name startswith /usr/bin
      output: "Binary file written (file=%fd.name)"
      priority: ERROR
      
    - rule: Launch Suspicious Container
      condition: >
        container.id != host and
        proc.name = "docker" and
        evt.args contains "exec"
      output: "Suspicious container launched (command=%proc.cmdline)"
      priority: WARNING