# NE PAS mettre de valeurs réelles ici
# Le secret est créé par le pipeline via GitHub Secrets
# Commande manuelle :
#   kubectl create secret generic devsecops-secret \
#     --from-literal=secret-key='votre-cle-secrete' \
#     --namespace=devsecops
apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secret
  namespace: devsecops
type: Opaque
data: {}
