apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-service
  namespace: devsecops
  labels:
    app: devsecops-app
    service: devsecops-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: NodePort  # Pour KIND
  selector:
    app: devsecops-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
  sessionAffinity: None