apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-service
  namespace: devsecops
spec:
  type: ClusterIP
  selector:
    app: devsecops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
